### ISSUE TITLE
Permissions error when using Letsencrypt certs

### ISSUE THREAD

**Issue by dewittn** [wildduck-email/zonemta-wildduck#2]
I was having trouble getting Zone-MTA to work with my Letsencrypt certificates I spent several hours trying to track down random SSL and TLS errors only to stumble upon the solution when I copied the certificates into the /etc/wildduck/certs/ directory. Eventually I was able to figure out that it was a permissions error that was causing the problem. 

What is weird to me it that I did no encounter this problem with any other part of the wild duck setup. Wildduck, Wildduck-webmail, and haraka all work fine, although I'm guessing it's because they don't use the use SSL connections, or it's handled by Nginx.

I understand the permissions issue is not necessarily a problem with the with the code or the setup, but it would have been helpful had this been clearly documented somewhere. I think even just add a comment in the interfaces/feeder.toml config could help.

```
# define keys for STARTTLS/TLS. These paths are relative to CWD
# Keys must be accessible by the 'wildduck' user or SMTP authentication will fail.
#key="./keys/example.com-key.pem"
#cert="./keys/example.com-cert.pem"
```
I'm happy to submit this as a pull request if needed.

**Comment by andris9** [comment]
Yeah, this could be unintuitive. ZoneMTA reads certificate files as running user, not as root. I added the suggested comment.
